### ISSUE TITLE
Param names without pattern

### ISSUE THREAD

**Issue by cesarnorena** [Rocketseat/gostack-template-conceitos-nodejs#5]
Almost all of the middlewares are using `request` and `response` but except one.
https://github.com/Rocketseat/gostack-template-conceitos-nodejs/blob/a9fc3305b7ed186be6eab51736786fc8c6acf236/src/app.js#L13
https://github.com/Rocketseat/gostack-template-conceitos-nodejs/blob/a9fc3305b7ed186be6eab51736786fc8c6acf236/src/app.js#L25

**Comment by pellizzetti** [comment]
Changed in #2!
